<?xml version="1.0" encoding="utf-8"?><Database Name="KMUReg_Demographic" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=KMUReg_Demographic;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="KMUReg_DemographicConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblUser" Member="tblUsers">
    <Type Name="tblUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstNameOf" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastNameOf" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StartDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EndDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="isInActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessTypeOf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblShamsiMiladi" Member="tblShamsiMiladis">
    <Type Name="tblShamsiMiladi">
      <Column Name="Miladi" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi_YearOf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi_MonthOf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi_DayOf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblShamsiMiladi" Member="tblShamsiMiladi1s">
    <Type Name="tblShamsiMiladi1">
      <Column Name="Miladi" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi_YearOf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi_MonthOf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi_DayOf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblHistory" Member="tblHistories">
    <Type Name="tblHistory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DiabetTypeLU" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDateOf" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Sore" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SoreDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoreLocationLeft" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoreLocationRight" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Laser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LaserDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LaserLocation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Debrid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DebridDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DebridLocation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Surgery" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SurgeryDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SurgeryLocationLeft" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SurgeryLocationRight" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gangrene" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GangreneDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GangreneLocation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Amputation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AmputationDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="AmputationLocation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Diseases" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Alcohol" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sigarret" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InPatient" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InPatientDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InPatientReason" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RegisteryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblRegistery_tblHistory" Member="tblRegistery" ThisKey="RegisteryID" OtherKey="ID" Type="tblRegistery" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblLabResult" Member="tblLabResults">
    <Type Name="tblLabResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FBS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="A1C" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LabDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Systol" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dyastol" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="O2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VitalSignDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="RegisteryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblRegistery_tblLabResult" Member="tblRegistery" ThisKey="RegisteryID" OtherKey="ID" Type="tblRegistery" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPhysicalExam" Member="tblPhysicalExams">
    <Type Name="tblPhysicalExam">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CC" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Sore" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SoreDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoreCountLeft" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoreCountRight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LargestLength" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoreLocationLeft" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoreLocationRight" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorstLeftSoreLU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorstRightSoreLU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Infection" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InfectionDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InfectionLocationLeft" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InfectionLocationRight" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Swell" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SwellDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SwellLocationLeft" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SwellLocationRight" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Neuropathy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DryLU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HeatLU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegisteryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblRegistery_tblPhysicalExam" Member="tblRegistery" ThisKey="RegisteryID" OtherKey="ID" Type="tblRegistery" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPrescription" Member="tblPrescriptions">
    <Type Name="tblPrescription">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Amputation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Surgery" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Debrid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Shoe" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Visit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Cover" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Consult" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Rehabilitation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Drug" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RegisteryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[FreeText]" Member="FreeText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="tblRegistery_tblPrescription" Member="tblRegistery" ThisKey="RegisteryID" OtherKey="ID" Type="tblRegistery" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblRegistery" Member="tblRegisteries">
    <Type Name="tblRegistery">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DemographicID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegDateOf" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="tblRegistery_tblHistory" Member="tblHistories" ThisKey="ID" OtherKey="RegisteryID" Type="tblHistory" />
      <Association Name="tblRegistery_tblLabResult" Member="tblLabResults" ThisKey="ID" OtherKey="RegisteryID" Type="tblLabResult" />
      <Association Name="tblRegistery_tblPhysicalExam" Member="tblPhysicalExams" ThisKey="ID" OtherKey="RegisteryID" Type="tblPhysicalExam" />
      <Association Name="tblRegistery_tblPrescription" Member="tblPrescriptions" ThisKey="ID" OtherKey="RegisteryID" Type="tblPrescription" />
    </Type>
  </Table>
  <Table Name="dbo.tblDemographic" Member="tblDemographics">
    <Type Name="tblDemographic">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileNo" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="NationalID" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="FirstNameOf" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastNameOf" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GenderLU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BirthDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HeightOf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeightOf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MarriageLU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CellNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PhoneNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="EducationLU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddressOf" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblShamsiMiladi" Member="tblShamsiMiladi2s">
    <Type Name="tblShamsiMiladi2">
      <Column Name="Miladi" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi_YearOf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi_MonthOf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi_DayOf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblLastFileNo" Member="tblLastFileNos">
    <Type Name="tblLastFileNo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LastFileNo" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="RegisteryNameOf" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>