<?xml version="1.0" encoding="utf-8"?><Database Name="KMUReg" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=KMUReg;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="KMURegConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblUser" Member="tblUsers">
    <Type Name="tblUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstNameOf" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastNameOf" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StartDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EndDateOf" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="isInActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessTypeOf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblShamsiMiladi" Member="tblShamsiMiladis">
    <Type Name="tblShamsiMiladi">
      <Column Name="Miladi" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi_YearOf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi_MonthOf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Shamsi_DayOf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>